POST http://localhost:3000/api/webhook/whatsapp
Content-Type: application/json

{
  "from": "5491121913619",
  "text": "Remi recuerdame mañana a las 10 comprar comida de mi perrito",
  "pushName": "Mauro"
}